# Generated by Django 5.1.2 on 2024-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('dairy', 'Dairy'), ('tools', 'Tools & Equipment'), ('seeds', 'Seeds & Saplings'), ('pesticides', 'Pesticides & Fertilizers'), ('organic', 'Organic Products'), ('livestock', 'Livestock & Feed'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
