# Generated by Django 5.1.2 on 2024-11-30 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The message sent by the user')),
                ('response', models.TextField(help_text='The response from the chatbot')),
                ('message_type', models.CharField(choices=[('general', 'General Query'), ('product', 'Product Related'), ('order', 'Order Related'), ('support', 'Customer Support'), ('weather', 'Weather Query'), ('market', 'Market Prices')], default='general', max_length=20)),
                ('is_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
